# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            PaPy
tagline:          'Parallel Pipelines in Python'
description:      'A parallel pipeline is a workflow, which consists of a series of connected processing steps to model computational processes and automate their execution in parallel on a single multi-core computer or an ad-hoc grid.'
url:              https://jich-mctp.github.io/calculate/
baseurl:          /

author:
  name:           'mcieslik'
  url:            https://github.com/mcieslik-mctp/papy

paginate:         5

# Custom vars
version:          2.1.0

github:
repo:           https://github.com/mcieslik-mctp/papy
